[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"
authors = ["George Smith <georgepetersmith@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
